### PR TITLE
FluentAvalonia v1.2 + New Sample App!

### LINKED ISSUE #73: Invalid TitleBar colors when switching themes
Hi,

Starting Sample application with Windows 10 in DarkMode, go to Settings and click on Set LightTheme. The application title become invisible, title bar min/max/close buttons also (unless you move pointer over them).
Same thing if your windows is in LightTheme and you try to change your Sample application theme to Dark.

I have tested this behaviour under Windows 10 (latest version) and Windows 11.
I don't know about Unbuntu nor MacOs.

Note: Whatever your Windows theme configuration, when you start your sample application, the titlebar colors are ok. The issue only happens when you switch to another theme from the Sample application. 

If you could have a look... 
This is not critical, but as I propose to change theme in my application as in your sample application, it would be great that this works correctly.

At the same time, have you noticed that in your sample application, let's say your windows is in Dark mode, you have a slim white border arroud your main window ?

### LINKED ISSUE #74: Numberbox doesn't update Value bound property when number is inputted using the textbox
**Describe the bug**
Numberbox does not update it's value if the user enters the value using the textbox and doesn't press enter, or click the spinner buttons(up/down buttons).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linus (Fedora)
 - FluentAvalonia Version: 1.1.8
 - Avalonia Version: 0.10.11

**Additional context**
For a settings page implementation, there are usually lots of controls for options. The user would most likely click other options as soon as they are done using the numberbox. Having the numberbox update it's value when input focus is lost would ensure the number set in it won't be lost if the user goes on to press a save botton.

### LINKED ISSUE #82: Menu Styles
FluentAvalonia seems to have bigger menu padding compared to WinUI. 

Here is the menu in Paint:
image

And here is the menu in FluentAvalonia:
image

The height of the MenuItem seems to be larger in FluentAvalonia than in WinUI

### PR DESCRIPTION
**Pull request by amwx**
FluentAvalonia v1.2 is finally here! Features several fixes, and improvements, and a new Sample App. First though, the change log

- Includes fixes from (#72 and #83). Note #83 introduced breaking changes in FluentAvaloniaTheme, mostly in property/method names.
- Includes PR #69 and #70
- Includes PR #84 

*Avalonia package
-Updated to Avalonia 0.10.12

*CoreWindow
-Resolved issue where titlebar colors wouldn't respect theme changes (fixes #73)
-Fixed issue where Titlebar would be too big on high dpi screens
-Added TitleBar property to CoreWindow, so no casting to ICoreApplicationView is necessary
-Other small improvements

*NavigationView
-Resolved issue where left pane items wouldn't remove top padding if back button was shown then hidden
-Removed bottom border from TopNavigationView (partial fix for #76)

*NumberBox
-Resolved issue where NumberBox wouldn't commit value on losing focus (fixes #74)
-Added DataValidationErrors to NumberBox template (#84, RobertBeekman)

*MenuItem / MenuFlyoutItem
-Fixed extra padding on MenuItems (fixes #82)

The new sample app is something I'm particularly proud of. I've managed to put Avalonia's animation system to the test, along with a completely refreshed look. The new app features an adaptive layout on control pages, better organization, uses AvaloniaEdit for code samples with ability copy code, and overall feels more modern. If you've used Win 11 and the new Microsoft store, you'll notice I've pulled a lot of inspiration from there.

image

Sample control page at full size
image

Sample control page at a smaller width
image

Included a page you can easily look up the resources that are used within Fluentv2. I know this theme quite well and even I need to constantly pull up the xaml file to remember what a resource is called.
image

Feel free to grab this branch and test it out before I merge!

### CODE REVIEW

**Comment by timunie** [comment]
Hi @amwx , 

I think this needs to be spread in the world. Am I allowed to share the link on Twitter and Telegram?

**Comment by emmauss** [comment]
Nice

**Comment by nlogozzo** [comment]
Such a great update! Thank you for all your hard work :)

**Comment by amwx** [comment]
> Hi @amwx ,
> 
> I think this needs to be spread in the world. Am I allowed to share the link on Twitter and Telegram?

Let me get it merged (that way at least I know everything is stable), but otherwise I don't care if you share links.

**Comment by robloo** [comment]
This looks great and the redesigned samples app is amazing!

**Comment by jmacato** [comment]
this looks good! :D glad to see more fluid animations there as well!

**Pull request merged**
