### PR TITLE
Begin testing/upgrade to Avalonia master/11.0

### PR DESCRIPTION
**Pull request by amwx**
A WIP, unstable branch for beginning to update with latest Avalonia master branch and all the breaking changes associated with the coming 11.0 release. For 11.0, FluentAvalonia will bump to v2.0. Not available yet, but I will eventually add a preview nuget package for any who which to begin upgrading. 

Current Avalonia build of this PR: 0.10.999-cibuild0019812-beta

Note if you clone this branch for personal testing:
- The code previews in the sample app are disabled as AvaloniaEdit is incompatible with master now
- This branch will be not be regularly updated, and may run somewhat out of date. The point of this is to allow me to make changes slowly to keep track of everything and not have to do it all at once when 11.0 is ready.
- This branch may be unstable as things are changed and updated

Checklist of things that need to be done from upstream changes:
- [ ] Remove `SplitButton` and `ToggleSplitButton` from FA.UI.Controls
    - [ ] Remove Sample pages and move control to "Core Controls" page
- [ ] Same for `DropDownButton`
- [ ] Awaiting https://github.com/AvaloniaUI/Avalonia/pull/7679 so control templates can be simplified
- [ ] Add FlowDirection support to CoreWindow
- [ ] Add styles for ManagedFileChooser which will be template-able in 11.0
- [ ] Remove separated `Border` element in control and use Brush transform where "Elevation" brushes are used (Buttons, TextBox, most notably)
- [ ] More as necessary...

Checklist of things pertaining to this library only:
- [ x ] Attempt to fix `CoreWindow` resizing when restoring the window (fixed in #140)
- [ ] PickerFlyoutPresenter change event args from object to EventArgs
- [ ] More as necessary...

### CODE REVIEW

**Comment by danielmayost** [comment]
i think your application work fine with `FlowDirection`, what needs to be updated?
image

(The exit of the text FluentAvalonia from the margins, is related to text processing and it is handled)

**Comment by amwx** [comment]
> i think your application work fine with `FlowDirection`, what needs to be updated? 
> (The exit of the text FluentAvalonia from the margins, is related to text processing and it is handled)

It's more I just need to make sure everything works, and make sure if in any of the controls I've ported had FlowDirection logic, I add that in now. Specifically for CoreWindow, I need to make sure the metrics reported for custom titlebar support is correct (since it's just an inverse scale transform, I'm not sure if I need to even do anything, but I need to double check). 
Also looks like the `SplitView` isn't respecting the RTL transform (it's rounded corner is still the top left)

> **Edit:** On second thought, you really need to update certain `Path`s as fixed LTR, such as V Glyph.
What do you mean? None of the icons are Paths, they're all coming from my Symbol font and rendered very similarly to `TextBlock`s. I'll check with that source if that needs adjusting. (note: this is my first real look at RTL related stuff, so pointers to things like this is really helpful)

**Comment by danielmayost** [comment]
Okay, `CipToBounds` does not respect `RenderTransform` at all, in WPF, `CipToBounds` does not affect render at all, only the layout, so I do not know if this is an expected behavior or a bug.
What can be done right now is to turn rounded edges to the right side.

As for Icons, it seems that in the Resources tab, the pencil illustration is reversed, right? You need to set all the icons that `FlowDirection = LTR`.

**Comment by robloo** [comment]
It should also be possible to redo the ColorPicker and make it match WinUI if you like. The way I'm building it in Avalonia is fully compositional/re-templatable. So you should just be able to use the existing components in some new styles, bind them together, and then have a fully functional picker. That's the plan at least.

I know ColorPicker isn't a priority for you so this is just an idea. It would be good to get alternative implementation using the same primitives (ColorSpectrum, ColorSlider, ColorPreviewer) though to make sure they are feature-complete.

**Comment by robloo** [comment]
Some other changes (some required):

 * (Useful) Use Loaded/Unloaded events
 * Rename PointerEnter to PointerEntered and PointerLeave to PointerExited per https://github.com/AvaloniaUI/Avalonia/pull/8396
 * I'm going to standardize a lot of the control template part names. That's likely going to require a few fixes on your end.

I'm happy to help with making any of these updates if you want.

Separately, I think I'm going to add a control template/style for the WinUI-designed vertical ColorPicker in Avalonia. That might allow you to remove ColorPicker here if you would like.

**Comment by amwx** [comment]
> Some other changes (some required):
> 
>     * (Useful) Use Loaded/Unloaded events
> 
>     * Rename PointerEnter to PointerEntered and PointerLeave to PointerExited per [Rename to PointerEntered and PointerExited AvaloniaUI/Avalonia#8396](https://github.com/AvaloniaUI/Avalonia/pull/8396)
> 
>     * I'm going to standardize a lot of the control template part names. That's likely going to require a few fixes on your end.
> 
> 
> I'm happy to help with making any of these updates if you want.
> 
> Separately, I think I'm going to add a control template/style for the WinUI-designed vertical ColorPicker in Avalonia. That might allow you to remove ColorPicker here if you would like.


Thanks. I'm keeping track myself of things to do (the list is getting too big haha). I'm waiting for the new renderer and all the styling system changes before I do anything further here as those are the biggest changes (particularly styling), also probably won't be much until at least the middle of July when I have more time. 

For template item names, I don't think there's much to do there. While I'd prefer the "PART_" convention not be forced on everyone, I know I'm on the losing side of that argument so I'm staying quiet. I honor that already though where controls use that in code, and as far as I know, the controls that use stuff in code follow that convention. And if it doesn't, it was probably me that ported it tbh

As for the ColorPicker, I have no intention of dropping support for the one I currently have. You probably won't like this, but I my current thought is to not provide support for the one you've been building upstream (no offense to you because from what I've seen it looks really good, but I already support one). What I haven't decided is if I'll replace some parts with the primitives upstream - that might be difficult since mine is built on my `Color2` struct and mixing that with Color and HsvColor upstream my not blend the best. This is probably lowest priority on my list though, and I'll probably want to benchmark some things first/give it a test run first.

**Comment by robloo** [comment]
>  also probably won't be much until at least the middle of July when I have more time.

No rush, I know it's a lot that's why I offered some of my time if you need it.

> While I'd prefer the "PART_" convention not be forced on everyone, I know I'm on the losing side of that argument so I'm staying quiet. I honor that already though where controls use that in code, and as far as I know, the controls that use stuff in code follow that convention.

Yea, I understand the "PART_" prefix was dropped for UWP/WinUI. It became very difficult to differentiate what part of control templates were referenced from code-behind and were almost mandatory when re-templating. So while UWP/WinUI follows standard XAML/C# naming conventions, there is a loss of information which is considered critical when re-templating. So I look at it as the lesser of two evils. I am only going to enforce this prefix on controls that are actually used in code-behind too. Styles should be allowed to name controls how they want otherwise.

> As for the ColorPicker, I have no intention of dropping support for the one I currently have. You probably won't like this, but I my current thought is to not provide support for the one you've been building upstream

That doesn't bother me. I also recall our past conversations on this and know your general thinking. I was only pushing for it again here to (1) reduce the maintenance burden on you and (2) it would be great if everyone could use a common set of primitives (3) If another project used the primitives that would be a good test to make sure they aren't missing anything major. I know the ColorPicker historically hasn't been standardized and I'm hoping the one I made upstream is generic enough it might change that going forward. However, we'll see. Otherwise, I'm a fan of everyone doing what they think is best outside of the core frameworks (in those we must largely agree). Time will tell the good ideas and we can all learn from each other.

**Comment by RobertBeekman** [comment]
Hi, I've been keeping an eye on the repository and I've noticed there hasn't been much activity as of recent.
I realize normal daily life goes on for all of us but @amwx, I was wondering if you're still committed to update the project to Avalonia 11? :)

I've just finished a 10 month rewrite of my project (Artemis)'s front-end and people really love the look FluentAvalonia provides and working with it has been a treat, so I'd really like to keep using FleuntAvalonia.

Thanks!

**Comment by robloo** [comment]
@amwx I can help upgrading controls and things as needed too.

**Comment by amwx** [comment]
@RobertBeekman Short answer - yes, FluentAvalonia will continue

First of all apologies on my lack of presence lately. I got caught up with something in July and then honestly needed a break and I clearly let time get away from me. I've missed quite a bit (both in this repo and upstream) so its going to take me a bit to get caught back up and get things rolling again. I'm going to ease back into things so I don't overwhelm myself but I am aiming to get a 11.0-preview1 compatible FluentAvalonia out probably within the first week or so of September. It looks like all the big things I was waiting on before proceeding here have been done upstream so once I get up to speed on the new styling system of control themes, and any other big things I missed, things will get moving again. 
I need to also take a look at the back log of issues and see if any need addressing so I can get those done before switching the master branch to be the FAv2/11.0 branch so that way it's easy for migrating everything over for myself and anyone that wants to help move controls over to control themes.

**Comment by timunie** [comment]
> First of all apologies on my lack of presence lately

Honestly, I don't think you need to apologies in any way! It's a free-time project I think and you should decide when you want to work on it. That said I'm happy that FA will continue, because I just ❤️ the styles and additional controls. If there's anything I can do to support (with time), let me know. 

Happy coding
Tim

**Comment by RobertBeekman** [comment]
That's great news, thanks for your message!

Like Tim said no need to be apologetic, I can understand it's sometimes difficult to summon the time and energy to work on a project like this as the main driving force.

Looking forward to what's to come and if it takes a while longer then that's that, we're in this for our enjoyment :).

**Comment by amwx** [comment]
Closing this PR. v2 work is now in a new branch and PR #188

**Pull request closed without merging**
