### PR TITLE
FA 2.1.0

### LINKED ISSUE #262: Soften Button Border Brushes
**Describe the bug**

Fluent v2 uses Acrylic Brushes for various borders -- including Button. Avalonia does not currently support Acrylic. Therefore, my assumption is FluentAvalonia uses the fallback values.

This results in button borders that are "too sharp" in dark theme (likely light as well).

To fix this, I would like to pre-blend the button border brush with the background brush taking into account the acrylic transparency as if it was there. This pre-blended color value would be the new border brush value. This means it would differ from WinUI numerically but look more visually similar (softening the button edges from a design standpoint). 

**Screenshots**

WinUI (using UWP, WinUI 2 Library, Windows 10 Pro):

image

FluentAvalonia:

image

**Desktop/Platform (please complete the following information):**
 - OS: [e.g. Windows (11/10), linux (distro), osx, wasm, etc]
 - FluentAvalonia Version [e.g. 1.0.0, or latest]
 - Avalonia Version [e.g. 0.10.10]

**Additional context**

I will fix this once direction is agreed.

### LINKED ISSUE #403: Animation for highlighting selected header in NavigationView
Would be great to have this animation implemented. It's a small detail but its absence really stands out.
Taskmgr_CPJuDYMKnO

### LINKED ISSUE #538: In High Contrast them, the selected item in a tab control is not underlined
In the High Contrast theme, the selected tab item is shown with a white underline (pipe) on a white background, so there is no visible indication of which tab is selected.

 - OS: Windows 11
 - FluentAvalonia Version: 2.0.5
 - Avalonia Version 11.0.9 & 11.0.10

I tried fixing it using a theme dictionary within my test app, but couldn't make it work.

```        
<ResourceDictionary x:Key="{x:Static sty:FluentAvaloniaTheme.HighContrastTheme}">
            <SolidColorBrush x:Key="TabItemHeaderSelectedPipeFill" Color="DodgerBlue" />
</ResourceDictionary>
```
Obviously, you wouldn't place a fixed color here, but probably link it to the system accent color -- but I was just testing.

### LINKED ISSUE #539: Task Dialog Hijacking Focus
**Describe the bug**
The TaskDialog uses OnLoaded to pull focus to either the default button, or the next item from KeyboardNavigationHandler. The issue is that when navigating between pages, once a component that has a TaskDialog with no default button specified in the XAML is loaded, the focus is pulled to the task dialog and then routed to the next item from the KeyboardNavigationHandler. This occurs without the TaskDialog being opened.

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10 & Windows 11 (Occurs on both)
 - FluentAvalonia Version: 2.0.5 (latest)
 - Avalonia Version: 11.0.10 (latest)

**Additional context**
The only way to avoid this behavior is to have a default button specified (which is not ideal for cases where the task dialog may contain a form to input data and when a user presses enter to submit a line of data we may not want to close the dialog from that), or to generate the TaskDialog in the code-behind to prevent the OnLoaded event from firing when the hosting component is rendered.

### LINKED ISSUE #542: Toggleable menu item not showing checkbox/radiobutton
**Describe the bug**
My apologies if this is a bit too soon, but I was already playing with FluentAvalonia 2.1.0 preview 1, and I noticed that the new menuitem feature introduced by Avalonia 11.1.0 doesn't seem to be supported yet.. (the addition of the ToggleType option on menu items)
Is it something planned? .. am I doing something wrong, or am I being rude for being too impatient?

**Screenshots**
image

image

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version 2.1.0 preview 1
 - Avalonia Version 11.1.0 beta 1

### LINKED ISSUE #543: NavigationView Footer Item Bug
So i just followed the code from the example of fluent avalonia NavigationView creation using the code behind of the view, it works just fine but when i set the "PaneDisplayMode" to LeftCompact the footer items disappear and reappear only upon opening the NavigationViewPane

**Screenshots**

--PaneDisplayMode = Left-- 

image

--PaneDisplayMode = LeftCompact--

image

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11 
 - FluentAvalonia Version  [latest]
 - Avalonia Version [11.0.10]

### LINKED ISSUE #546: Text disappears from Editable TextBox
Using the following XAML to define a main window:
```
<Window xmlns="https://github.com/avaloniaui"
     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
     xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
     xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
     xmlns:fa="using:FluentAvalonia.UI.Controls"
     mc:Ignorable="d" d:DesignWidth="400" d:DesignHeight="400"
     Width="400" Height="400"
     x:Class="ComboBox.MainWindow"
     Title="ComboBox">
  <StackPanel Orientation="Vertical">
    <TextBlock Text="An editable ComboBox:" Margin="5,5,0,0" />
    <fa:FAComboBox Name="ComboBox"
          Margin="10,5,0,0"
          IsEditable="true"
          >
      <fa:FAComboBoxItem Content="One" />
      <fa:FAComboBoxItem Content="Two" />
      <fa:FAComboBoxItem Content="Three" />
      <fa:FAComboBoxItem Content="Four" />
      <fa:FAComboBoxItem Content="Five" />
    </fa:FAComboBox>
    <TextBlock Text="A TextBox:" Margin="5,10,0,0" />
    <TextBox Name="TextBox" Margin="10,5,0,0" />
  </StackPanel>
</Window>
```
Click in the editable area of the FAComboBox.  Type some text ( eg. "Pi").  Click in the TextBox (or tab to it).  Observe that the text in the ComboBox disappears.  Put focus back on the ComboBox.  The text reappears.  Shift the focus away, and the text disappears again.  Go back and the text reappears.

Next, select an item from the dropdown list.  This does not disappear when shifting focus away from the FAComboBox.

Next, type some text in the FAComboBox. Now, when focus is shifted away from it, the text no longer disappears.

**Desktop/Platform (please complete the following information):**
 - OS: Linux (Armbian 24.2.1 bookworm)
 - FluentAvalonia Version: 2.0.5 and 2.1.0-preview1
 - Avalonia Version: 11.0.10 and 11.1.0-beta1

### LINKED ISSUE #552: TabView border disappears when there is a single tab only
**Describe the bug**
When using the TabView component, the border to the right of the tab disappears if there is just one item in the TabView list. Not sure if this is intentional or not, it can easily be styled. That being said, the right border arc does disappear when the tab is empty.

```     
<Style Selector="ui|TabView /template/ ContentPresenter">
      <Setter Property="BorderBrush">
          <Setter.Value>
              <SolidColorBrush Opacity="1" Color="{DynamicResource TabViewBorderBrush}" />
          </Setter.Value>
      </Setter>
      <Setter Property="BorderThickness" Value="0,0,0,1" />
  </Style>
```
Border visible on multiple tabs:
image

Border gone when there's a single tabview item:

image

**Desktop/Platform:**
 - OS: Windows 11
 - FluentAvalonia Version 2.1.0 and current
 - Avalonia Version  11.1.0-beta1

### PR DESCRIPTION
**Pull request by amwx**
- Removes Hyperlink Button in FluentAvalonia and use built-in Avalonia one
- Removes usages of FABorder in the control library
- Hopefully fixes #539, only initializing `TaskDialog` if it is being opened
- Addressed an issue for TabControl/TabStrip where the selection indicator won't show in HighContrast theme) (fixes #538)

[Added in Preview 2]
- PR #553 (upstream fixes)
- Fixed an issue with TabView border not displaying, fixes #552 
- Added support for MenuItem Toggle for Avalonia MenuItem, closes #542
- Updated some NavigationView code to WinUI 1.5, fixes #543

[Preview 3 / 4]
(Skip Preview 3)
- Fixes #546
- Replaced `Avalonia.Controls.ItemsRepeater` with separate port now available in this library.
- Added `ProgressRing` control
- Added NavigationView selection indicator animation

<s>Preview package available: 2.1.0-preview1</s>

Closes #262 
Closes #403

### CODE REVIEW

**Comment by robloo** [comment]
This is great!

I still intend to do the other things in my roll-up list. However, it's going to be about 3 weeks before I have time to look at them.

**Comment by robloo** [comment]
@amwx We can also close https://github.com/amwx/FluentAvalonia/issues/262 with this PR which is using BackgroundSizing across the board now.

**Comment by amwx** [comment]
Preview2 Package has been pushed out with more ongoing fixes.

**Comment by amwx** [comment]
Coming in 2.1 - NavigationView Selection Indicator animation!

https://github.com/amwx/FluentAvalonia/assets/40413319/be1abfd1-13b1-4b55-929c-e33197b18d9f

**Comment by amwx** [comment]
Preview 3 package has been pushed. Note, as of this preview, the implicit reference to `Avalonia.Controls.ItemsRepeater` no longer exists. FA now has a port of the ItemsRepeater itself and all usages (namely NavigationView) have been switched over. There's still more work to do around the ItemsRepeater, but its nothing that should interfere with using it.

Also, the package/branch is still on Avalonia11.1 beta 1 (I don't think there's anything breaking in beta 2 that would mean you can't use it, but just putting it out there)

**Comment by robloo** [comment]
I pulled in the preview3 package in an existing app and am getting crashes on startup every time with the NavigationView > ItemsRepeater. Will take a look more later.

**Comment by amwx** [comment]
Just pushed Preview 4, with a fix for the ItemsRepeater and ProgressRing.

**Comment by robloo** [comment]
@amwx I'm still seeing `ItemsRepeater` crashes: https://github.com/amwx/FluentAvalonia/issues/564

I also opened another PR: https://github.com/amwx/FluentAvalonia/pull/562 (unrelated)

**Comment by amwx** [comment]
Preview5 package pushed. Should make ItemsRepeater usable now (and therefore NavigationView). `FABorder` has also now been removed (shouldn't affect anyone unless you were copying styles for a control that used it) and updates all the usages within the FA sample app back to a regular Border.

**Comment by amwx** [comment]
Preview6 just pushed with the fixes in the above commits.

Note to AppWindow users:
I am aware of some issues that have arisen with AppWindow. The issue in #573 should be resolved with a PR in master for Avalonia (no idea if it will make it into 11.1 or not). I mentioned another issue in my comment in 573 about some issues if you Maximize->Minimize->Restore. Avalonia PR 14470 is what broke it because that PR started messing with the restore rectangle for the Win32 window and it throws some things off. No idea what to do about it

**Comment by Anequit** [comment]
Is this the intended color for these buttons?
image

**Comment by IsaacMarovitz** [comment]
ToggleType menus seem to have some problems.

If a Checkbox MenuItem is created with IsChecked disabled and no other ToggleType'd MenuItems are present it is shown as this:

Screenshot 2024-07-17 at 17 54 09

Toggling it produces this:

Screenshot 2024-07-17 at 17 54 23

And toggling it again results in this:

Screenshot 2024-07-17 at 17 54 44

IMO, it should be rendered initially like the last state.

**Pull request merged**
